"""Register a local JPEG/PNG as the current shot first frame. No image providers."""
from __future__ import annotations

from ..database import connect
from ..services.asset_service import persist_binary_asset
from ..services.keyframe_service import select_shot_keyframes
from ..services.media_transfer_service import (
    MAX_LOCAL_IMAGE_BYTES,
    MediaTransferError,
    sniff_raster_image,
)
from ..services.project_service import get_project


class LocalKeyframeError(RuntimeError):
    def __init__(self, code: str, message: str) -> None:
        self.code = code
        super().__init__(message)


def register_local_first_frame(project_id: str, shot_id: str, content: bytes, *, filename: str = "") -> dict:
    project = get_project(project_id)
    if not project:
        raise LocalKeyframeError("PROJECT_NOT_FOUND", "项目不存在。")
    if not any(shot.get("id") == shot_id for shot in project.get("shots") or []):
        raise LocalKeyframeError("SHOT_NOT_FOUND", "镜头不存在。请先确认分镜再登记首帧。")
    if not content:
        raise LocalKeyframeError("EMPTY_FILE", "请选择一张 JPEG 或 PNG 图片。")
    if len(content) > MAX_LOCAL_IMAGE_BYTES:
        raise LocalKeyframeError("IMAGE_TOO_LARGE", "图片超过 12MB 上限，请压缩后再登记。")
    try:
        mime_type, suffix = sniff_raster_image(content, register_only=True)
    except MediaTransferError as exc:
        raise LocalKeyframeError(exc.code, _chinese(exc)) from exc
    if suffix not in {".png", ".jpg", ".jpeg"}:
        raise LocalKeyframeError("UNSUPPORTED_IMAGE_FORMAT", "只接受 JPEG 或 PNG。")

    asset_id = persist_binary_asset(
        project_id,
        "first-frame",
        "本地登记首帧",
        "User-registered local JPEG/PNG first frame. Not generated by an image provider.",
        "local-register",
        content,
        suffix,
        "local-register",
        "user-upload",
    )
    public_path = _asset_path(asset_id)
    result = select_shot_keyframes(project_id, shot_id, first_frame_path=public_path, last_frame_path=None)
    return {
        "ok": True,
        "asset_id": asset_id,
        "file_path": public_path,
        "mime_type": mime_type,
        "byte_size": len(content),
        "role": "first_frame",
        "asset_type": "first-frame",
        "registered": True,
        "source": "local-register",
        "filename_hint": _safe_name(filename),
        "project_id": project_id,
        "shot_id": shot_id,
        "shot": result,
    }


def _asset_path(asset_id: str) -> str:
    with connect() as conn:
        row = conn.execute("SELECT file_path FROM assets WHERE id = ?", (asset_id,)).fetchone()
    if not row:
        raise LocalKeyframeError("ASSET_NOT_FOUND", "登记后未能读取资产路径。")
    return row["file_path"]


def _safe_name(name: str) -> str:
    base = (name or "").replace("\\", "/").split("/")[-1]
    return base[:80]


def _chinese(exc: MediaTransferError) -> str:
    if exc.code == "SVG_NOT_ALLOWED":
        return "不能登记 SVG。请选择 JPEG 或 PNG。"
    if exc.code == "UNSUPPORTED_IMAGE_FORMAT":
        return "只接受 JPEG 或 PNG，且文件内容必须与格式一致。"
    return str(exc)
